version: "3.7"
services:
    edc-my-credentials:
        build: .
        ports:
        - 5000:5000
        volumes:
        - .:/srv/service
        env_file:
          - "./test_environment.env"
        command: uvicorn --host=0.0.0.0 --port 5000 --log-level=info byoa_results:app --workers 3
